name: ci

on: pull_request

env:
  # ideally this shouldn't be needed because we have a .swift-version file.
  # see https://github.com/swiftlang/swiftly/issues/517
  swift_version: "6.2.4"

jobs:
  # unfortunately we need different installation methods for each OS. see:
  # macos: https://github.com/vapor/swiftly-action/pull/8
  # windows: https://github.com/swiftlang/swiftly/issues/151
  build-macos:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "install swiftly"
        run: |
          brew install swiftly
          swiftly init --skip-install
          swiftly install $swift_version
          swiftly use $swift_version
      - name: build
        run: |
          . "/Users/runner/.swiftly/env.sh"
          swift build -c release
      - uses: actions/upload-artifact@v7
        with:
          name: macos
          path: .build/release/projectx
  build-linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "install swiftly"
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ env.swift_version }}
      - name: build
        run: swift build -c release --static-swift-stdlib
      - uses: actions/upload-artifact@v7
        with:
          name: linux
          path: .build/release/projectx
  build-windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: compnerd/gha-setup-swift@v0.4.0
        with:
          swift-version: swift-${{ env.swift_version }}-release
          swift-build: ${{ env.swift_version }}-RELEASE
      - name: build
        run: swift build -c release
      - uses: actions/upload-artifact@v7
        with:
          name: windows
          path: .build/release/projectx.exe
  static_checks:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: vapor/swiftly-action@v0.2.1
        with:
          toolchain: ${{ env.swift_version }}
      - run: swift format lint --recursive --strict .