name: ci

on: pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: swift build
  static_checks:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint --recursive --strict .